export const AUTHPROVIDER =  "useAuth must be used within an AuthProvider."
export const EMAILIDNOTREGISTERED =  "Email ID is not registered in the database."
export const USERNAMEORPASSWORDINCORRECT =  "Username or password entered is incorrect."
export const ERROROCCURED =  "An error occurred. Please try again."
export const SIGNUPSUCCESS =  "Signup successful!"
export const LOGGEDOUTSUCCESS =  "Logged out successfully."

export const FAILEDTOFETCH =  "Failed to fetch items."
export const ITEMADDEDSUCCESS =  "Item added successfully."
export const FAILEDTOADD =  "Failed to add item."
export const ITEMUPDATESUCCESS =  "Item updated successfully."
export const FAILEDTOUPDATE =  "Failed to update item."
export const ITEMDELETESUCCESS =  "Item deleted successfully."
export const FAILEDTODELETE =  "Failed to delete item."
export const ORDERUPDATE =  "Order updated successfully."
export const FAILEUPDATEORDER =  "Failed to update order."